// <auto-generated />
namespace FIRE.X.DL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class More_Precision : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(More_Precision));
        
        string IMigrationMetadata.Id
        {
            get { return "201908211411144_More_Precision"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
