// <auto-generated />
namespace FIRE.X.DL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_balance_to_transactions : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_balance_to_transactions));
        
        string IMigrationMetadata.Id
        {
            get { return "201908050901282_add_balance_to_transactions"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
